all:
	go-bindata -pkg binhtml -o binhtml/assert.go template/
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o airdisk.linux main.go
	CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o airdisk.windows main.go
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o airdisk.darwin main.go
